name: Remove Needs Work Tag on PR Update

on:
  pull_request_target:
    types:
      - synchronize
      - closed
      
permissions:
  issues: write
  pull-requests: write

jobs:
  remove-issue-tag:
    name: Remove needs work label
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            needs work
